// ui/angular/projects/bpw-wcm-rendering/src/lib/rendering/resource-renderer/resource-renderer.component.ts
import {
  Component,
  OnInit,
  OnDestroy,
  Input,
  AfterViewInit,
  ViewEncapsulation,
} from "@angular/core";
import { BehaviorSubject } from "rxjs";
import { filter } from "rxjs/operators";
import { DomSanitizer } from "@angular/platform-browser";
import {
  RenderTemplate,
  ContentItem,
  ContentItemService,
  RendererService,
} from "bpw-wcm-service";

//https://blog.angularindepth.com/building-an-aot-friendly-dynamic-content-outlet-in-angular-59c1a96171a
@Component({
  selector: "resource-renderer",
  templateUrl: "./resource-renderer.component.html",
  styleUrls: ["./resource-renderer.component.scss"],
  encapsulation: ViewEncapsulation.None,
})
export class ResourceRendererComponent
  implements OnInit, OnDestroy, AfterViewInit {
  @Input() renderer;
  @Input() siteAreaKey: string;
  @Input() rendererTemplate: RenderTemplate;
  @Input() contentPath: string;
  @Input() repository: string;
  @Input() workspace: string;
  @Input() contentPathIndex: number;
  contentItemChange = new BehaviorSubject<ContentItem>(null);
  contentItem: ContentItem = null;

  constructor(
    private contentItemService: ContentItemService,
    private sanitizer: DomSanitizer,
    private rendererService: RendererService
  ) {
  }

  ngOnInit() {
    this.sanitizer.bypassSecurityTrustHtml(this.rendererTemplate.code);
    this.contentItemService
      .getContentItem(this.repository, this.workspace, this.contentPath)
      .pipe(filter((item) => !!item))
      .subscribe((contentItem: ContentItem) => {
        this.contentItem = contentItem;
        this.rendererService.addContentItem(this.contentId(), this.contentItem);
        this.contentItemChange.next(this.contentItem);
      });
  }

  ngAfterViewInit() {
    this.contentItemChange.subscribe((contentItem) => {
      if (contentItem != null) {
        if (this.renderCode()) {
          const content = document.getElementById(
            `resource-viewer-${this.contentId()}`
          );
          content.innerHTML = this.elementRenderContent(contentItem);
        } else {
          this.rendererTemplate.rows.forEach((row) =>
            row.columns.forEach((column) =>
              column.elements.forEach((element) => {
                const content = document.getElementById(
                  `resource-viewer-${this.contentId()}-${element.name}`
                );
                content.innerHTML = this._contentElement(
                  contentItem,
                  element.name
                );
              })
            )
          );
        }
      }
    });
  }

  ngOnDestroy() {
    this.contentItemChange.unsubscribe();
  }
  contentId(): string {
    return `${this.siteAreaKey}_${this.renderer}_${this.contentPathIndex}`;
  }

  renderCode(): boolean {
    return this.rendererTemplate.code != undefined;
  }

  renderLayout(): boolean {
    return this.rendererTemplate.rows != undefined;
  }

  elementRenderContent(contentItem: ContentItem): string {
    let result = `${this.rendererTemplate.code}`
      .replace(
        "<render-element ",
        `<render-element content='${this.contentId()}' `
      )
      .replace(
        "<render-property ",
        `<render-property content='${this.contentId()}' `
      );

    return this._resolveWidgetBody(result);
  }

  isElement(source: string): boolean {
    return "element" === source;
  }

  isProperty(source: string): boolean {
    return "property" === source;
  }

  isWidget(source: string): boolean {
    return "widget" === source;
  }

  private _contentElement(contentItem, elementName: string): string {
    return (
      contentItem.elements[elementName] ||
      contentItem.properties[elementName] ||
      ""
    );
  }

  _resolveWidgetBody(content: string) {
    var regex = /\$\{.*?\}/g;
    let matches = content.match(regex);

    let result = content;
    if (matches) {
      for (let matche of matches) {
        let data = matche
          .substring(2, matche.length - 1)
          .trim()
          .split(":");
        if (data[0] === "elements") {
          result = result.replace(matche, this.contentItem.elements[data[1]]);
        } else if (data[0] === "properties") {
          result = result.replace(matche, this.contentItem.properties[data[1]]);
        }
      }
    }
    return result;
  }
}

<div
  class="card, content-item-layout"
  *ngIf="renderCode()"
  id="resource-viewer-{{ contentId() }}"
></div>
<div class="card, content-item-layout">
  <ng-container *ngIf="renderLayout()">
    <div
      class="card container"
      fxLayout="row"
      style="padding: 6px"
      *ngFor="let row of rendererTemplate.rows; let rowIndex = index"
    >
      <div
        fxLayout="column"
        *ngFor="let column of row.columns; let columnIndex = index"
        fxLayoutAlign="start"
        fxFlex="{{ column.width ? column.width : 100 }}"
      >
        <div
          fxLayout="row"
          id="resource-viewer-{{ contentId() }}-{{ element.name }}"
          *ngFor="let element of column.elements; let elementIndex = index"
          fxLayoutAlign="start"
          fxFlex="{{ column.width ? column.width : 100 }}"
        >
          <!--
          <render-element
            *ngIf="isElement(element.source)"
            content="{{ contentId() }}"
            element="{{ element.name }}"
          ></render-element>
          <render-property
            *ngIf="isProperty(element.source)"
            content="{{ contentId() }}"
            property="{{ element.name }}"
          >
          </render-property>
          <render-fragement
            *ngIf="isWidget(element.source)"
            content="{{ contentId() }}"
            body="{{ element.body }}"
          >
          </render-fragement>
          -->
        </div>
      </div>
    </div>
  </ng-container>
</div>

// ui/react/react-wcm-skeleton/src/bpw-wcm/elements/ResourceRenderer/ResourceRenderer.tsx
import React, { useContext, useEffect, useState } from 'react';
import { tap } from 'rxjs/operators';
import AppContext from 'bpw-common/AppContext';
import JsxParser from 'react-jsx-parser';
import contentItemService from '../../services/ContentItemService';
function ResourceRenderer(props) {
  const { wcmElements } = useContext(AppContext);
  const { repository, workspace, siteAreaKey, rendererTemplate, renderer, contentPathIndex, contentPath } = props;
  const [contentItem, setContentItem] = useState(null);
  useEffect(() => {
    contentItemService
      .getContentItem(repository, workspace, contentPath)
      .pipe(tap((contentItem) => setContentItem(contentItem)))
      .subscribe();
    //todo, clean it up
  }, [contentPath]);

  function renderCode() {
    return rendererTemplate.code !== undefined;
  }

  function renderLayout() {
    return rendererTemplate.rows !== undefined;
  }

  function elementRenderContent(contentItem) {
    let result = `${rendererTemplate.code}`
      .replace('<render-element ', `<render-element content={${JSON.stringify(contentItem)}} `)
      .replace('<render-property ', `<render-property content={${JSON.stringify(contentItem)}} `);

    return _resolveWidgetBody(result);
  }

  function _resolveWidgetBody(content) {
    var regex = /\$\{.*?\}/g;
    let matches = content.match(regex);

    let result = content;
    if (matches) {
      for (let matche of matches) {
        let data = matche
          .substring(2, matche.length - 1)
          .trim()
          .split(':');
        if (data[0] === 'elements') {
          result = result.replace(matche, contentItem.elements[data[1]]);
        } else if (data[0] === 'properties') {
          result = result.replace(matche, contentItem.properties[data[1]]);
        }
      }
    }
    return result;
  }

  function _contentElement(contentItem, elementName) {
    return contentItem.elements[elementName] || contentItem.properties[elementName] || '';
  }
  return (
    <>
      {contentItem && renderCode() && <JsxParser components={wcmElements} jsx={elementRenderContent(contentItem)} />}
      {contentItem &&
        renderLayout() &&
        rendererTemplate.rows.map((row, rowIndex) => (
          <div key={rowIndex} className="card container" style={{ flexDirection: 'row', padding: '6px' }}>
            {row.columns.map((column, columnIndex) => (
              <div key={columnIndex} style={{ flexDirection: 'column', layoutAlign: 'start', flex: column.width ? column.width : 100 }}>
                {column.elements.map((element, elementIndex) => (
                  <div key={elementIndex} style={{ flexDirection: 'row', layoutAlign: 'start', flex: 'column.width ? column.width : 100' }}>
                    {rendererTemplate.rows.map((rtRow, rtRowIndex) => {
                      return (
                        <div key={rtRowIndex}>
                          {rtRow.columns.map((rtColumn, rtColumnIndex) => {
                            return (
                              <div key={rtColumnIndex}>
                                {rtColumn.elements.map((element, rtElementIndex) => (
                                  <JsxParser
                                    key={`${rtRowIndex}_${rtColumnIndex}_${rtElementIndex}`}
                                    components={wcmElements}
                                    jsx={_contentElement(contentItem, element.name)}
                                  />
                                ))}
                              </div>
                            );
                          })}
                        </div>
                      );
                    })}
                  </div>
                ))}
              </div>
            ))}
          </div>
        ))}
    </>
  );
}
export default ResourceRenderer;
